name: Spectrum Gateway Deploy

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_CLUSTER: spectrum-cluster
  GKE_ZONE_OR_REGION: us-central1
  DEPLOYMENT_NAME: spectrum-gateway
  NAMESPACE: dev
  DOCKER_IMAGE_NAME: cgpradeepkumar/spectrum-gateway
  DOCKER_IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT }}
          version: latest

      - name: Install gke-gcloud-auth-plugin
        run: gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --region ${{ env.GKE_ZONE_OR_REGION }}

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: latest

      - name: Deploy with Helm
        run: |
          helm upgrade --install ${{ env.DEPLOYMENT_NAME }} ./charts \
            --set image.repository=${{ env.DOCKER_IMAGE_NAME }} \
            --set image.tag=latest \
            --namespace ${{ env.NAMESPACE }} --create-namespace

